# Generated by Django 5.1.3 on 2024-12-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_alter_process_title_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_leaf', models.BooleanField(default=False)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='processes.process')),
            ],
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
