# Generated by Django 5.1.3 on 2024-12-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_task_delete_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='linked_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_task', to='processes.process'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
    ]
