# Generated by Django 5.1.3 on 2024-12-23 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_task_linked_process_alter_task_is_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='processes.process'),
        ),
    ]
