# Generated by Django 5.1.3 on 2024-12-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_rename_description_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.JSONField(),
        ),
    ]
