# Generated by Django 5.1.3 on 2024-12-31 21:01

import processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.JSONField(default=processes.models.get_default_content),
        ),
    ]
