# Generated by Django 5.1.3 on 2025-01-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_alter_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
