# Generated by Django 5.1.3 on 2025-01-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.AddField(
            model_name='process',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='processes.team'),
        ),
    ]
