# Generated by Django 5.1.3 on 2025-01-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_remove_task_team_process_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='processes.team'),
        ),
    ]
