# Generated by Django 5.1.3 on 2025-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_alter_process_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='lastOpened',
            field=models.DateTimeField(null=True),
        ),
    ]
