# Generated by Django 5.1.3 on 2025-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_process_lastopened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='isPrimary',
            new_name='is_primary',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='lastOpened',
            new_name='last_opened',
        ),
    ]
