# Generated by Django 5.1.3 on 2025-01-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_rename_isprimary_process_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.team'),
        ),
    ]
