# Generated by Django 5.1.3 on 2025-01-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_alter_process_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='parent_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.process'),
        ),
    ]
